drop table if exists Book;
create table Book (
    id bigint generated by default as identity,
    name varchar,
    author varchar,
    summary varchar,
    companyName varchar,
    primary key (id)
);